### ISSUE TITLE
Idea: Support for solar power

### ISSUE THREAD

**Issue by ndbroadbent** [rbaron/b-parasite#108]
I saw this project a little while ago where someone hacked a bluetooth thermometer to power it with a solar panel and supercap instead of a coin cell: https://hackaday.io/project/177910-solar-powered-bluetooth-thermometer-with-supercap

I was thinking that this could be a good fit for the b-parasite, especially since plants need sun. And I just like the idea of a little device that runs forever, where I never need to change the battery.

Actually it probably wouldn't be too hard to perform the same hack on the current design, but maybe the PCB and case could be modified slightly to support a solar panel. I have a little bit of experience but am still very much a noob, but I could give it a go. Is there a wiki or something where people can submit variations?

**Comment by rbaron** [comment]
Hey @ndbroadbent,

I'm happy to mention your variant on the Wiki once you have it working.
