### ISSUE TITLE
Hardware 1.2.0 vs 2.0.0

### ISSUE THREAD

**Issue by nyok92** [rbaron/b-parasite#111]
Hi @rbaron ,
Which hardware revision would you advise between 1.2.0 and v2 ? 
If i understand the v2 adds 2 switches (Reset and Sw1) and full rework of the PCB, and components.
 
Will I be able to build and flash the firmware on v2 ? ( which branch should I use ? )
Is it tested and working correctly aginst the Hardware version 2 ?

As there is a component shortage on E73-2G4M08S1C-52840, i swapped it with E73-2G4M08S1CX-52840.
This one doesn't come with the built in antenna, do you had feedback about it ? Order a specific one to integrate with ?

If i understand it well, there are differents sizes for the  SoC on the PCB, do you plan to build the firmware towards another chip ?  (like E83-2G4M03S ) ?
![image](https://user-images.githubusercontent.com/40342954/225350680-025df1d2-d1c6-4e9c-8aa7-1197f1da9fed.png)

Is there any issues in my following components placement ?

![image](https://user-images.githubusercontent.com/40342954/225350072-6c96d742-c69a-4b83-9a96-ba04923f061b.png)

Thanks

**Comment by rbaron** [comment]
Hi @nyok92,

V2.0.0 is still under early development. There's no software support nor calibration nor testing for it yet. I don't have an estimate on when it will be ready. I recommend going with 1.2.0 in the master branch. 

I have never used the CX chip variant, but some users have had success with them, as they are apparently pin compatible with the C version. You may find relevant info in the existing issues.
