### ISSUE TITLE
Q4 orientation in Hardware 2.0

### ISSUE THREAD

**Issue by Helmi** [rbaron/b-parasite#119]
I just ordered with JLCPCB this morning and similar to #42 and #106 their engineers are getting back to me regarding Q4 orientation.

They don't suggest to change it but ask to confirm it. Not being the hardware professional myself I'm unsure about that.

Can anyone help confirming the orientation with the collector down and emitter up in HW2?

![Produce_DanZhi SMT_Snapshot Top 5855045A_Y1 SMT02304151205207](https://user-images.githubusercontent.com/175346/232210733-903c9bbc-9f9b-410a-bfba-78543e2747ab.png)

**Comment by rbaron** [comment]
Hi @Helmi,

Please refer to the [Wiki](https://github.com/rbaron/b-parasite/wiki/How-to-order:-PCB-fabrication-and-SMT-assembly#photodiode-q4).

**Comment by Helmi** [comment]
Hmm but the wiki refers to Hardware 1.2 only, or did I miss something? If the footprint dot is still the valid reference I'd suggest updating the headline so this is clearly also valid for HW 2.0.

**Comment by rbaron** [comment]
Yes, the dot is still the reference. Updated it.
