### ISSUE TITLE
Feature request/question/opinion - longer probe

### ISSUE THREAD

**Issue by RobertLukan** [rbaron/b-parasite#131]
I am currently building BLE/LTE proxy software with Thing91 from Nordic. My goal is to capture moisture of soil at the farm land, while I dont have any power and connectivity there. I have a very basic software ready, but still a lot missing. I was thinking redesigning the hardware a bit. I would like to get soil moisture slightly deeper. Could I just extended the probe while retaining capacitive field same size ? Will I need to recalibrate it ? Another option is to make the capacitive probe longer, maybe making it narrower ?

Any opinion is welcome. I will try to document this small project once is alive.

**Comment by rbaron** [comment]
Hi @RobertLukan, some users have adapted the project to better fit their different needs. Examples: #74, #69. You would most likely need to recalibrate the sensor if you change the hardware.
