### ISSUE TITLE
R9 has no position in kicad/parasite-top-pos.csv

### ISSUE THREAD

**Issue by nordeep** [rbaron/b-parasite#15]
Seems R9 has no position in [kicad/parasite-top-pos.csv](https://github.com/rbaron/b-parasite/blob/main/kicad/parasite-top-pos.csv), but exist in BOM [kicad/parasite.csv](https://github.com/rbaron/b-parasite/blob/main/kicad/parasite.csv).
This is confusing when trying to place an order on JLCPCB. It seems that it is necessary to clarify in documentation.

**Comment by rbaron** [comment]
The R9 in this revision is a through-hole photoresistor, which I believe JLCPCB does not assemble. I will update the wiki for ordering to reflect that.
