### ISSUE TITLE
Q4 orientation question from JLCPCD (I've read related docs and issues)

### ISSUE THREAD

**Issue by ScottG489** [rbaron/b-parasite#169]
So I got the seemingly common email from JLCPCB regarding the polarity of the Q4 component. The docs say that the collector (C) should be aligned with the "footprint dot". In the picture they sent (below) it seems like the footprint dot is on the bottom next to the emitter (E) which is wrong.

Do I have this correct? **Should I tell them something along the lines of: "The component as pictured is wrong. Please reverse the polarity of the Q4 component"?**

Further evidence of this, it looks like the R10 component connects to E in the pic from the docs, but in the picture they sent me it connects to C.

Also there's another issue (#42) that seems very similar to what I'm seeing. In it @rbaron comments saying that JLCPCB's "suggestion" is wrong. It's not clear to me though if this picture they sent me is their "suggestion". It just seems to be how they're seeing it and asking for me to confirm if it's correct.

Image sent from JLCPCB:
<img width="100" height="588" alt="Screenshot 2023-12-01 at 9 08 14 AM" src="https://github.com/rbaron/b-parasite/assets/910809/e2038456-ea1f-4809-9fdb-13c90314168d">

If this is the case, what is the reason this was wrong? This is my first time ordering a PCB, but I very carefully followed the directions and uploaded the files from the [How to order](https://github.com/rbaron/b-parasite/wiki/How-to-order:-PCB-fabrication-and-SMT-assembly) docs.

Also it doesn't matter too much, but [the picture in the docs](https://github.com/rbaron/b-parasite/wiki/How-to-order:-PCB-fabrication-and-SMT-assembly#photodiode-q4) looks different than what it seems the current PCB layout is. For example, in the latest PCB layout there isn't a "PHT" component and the Q4 component is laid out vertically, not horizontally like in the docs. I'd be happy to submit an updated image in a PR if that would make sense.

**Comment by rbaron** [comment]
Hey @ScottG489,

The collector C should indeed be aligned with the dot, so facing down in the v2.0.0 like this:

![image](https://github.com/rbaron/b-parasite/assets/1573409/ea12c517-591f-40f8-97e0-fbb28580975e)

I don't know exactly why sometimes this happens. The last time I submitted an order, it required no correction. But other times I had to request the change, using the same placement file. 

I will update the wiki with the tip for the newest hardware revision.

**Comment by ScottG489** [comment]
Hey thanks so much for the quick reply. And for this great project!

Maybe it just comes down to the engineer that looks at it. Because if I go into my orders and look at the PCB layout, it looks correct (with the C aligned with the dot).

I've messaged them to let them know it should be the reverse of how they have it in the picture they sent me. I also let them know of the common confusion with this PCB and if there's something we could do to avoid it in the future. I'll ping you here if they come back with anything helpful. Thanks again!
