### ISSUE TITLE
WIKI link pogo pins not avilable

### ISSUE THREAD

**Issue by eiten** [rbaron/b-parasite#215]
In the wiki on page https://github.com/rbaron/b-parasite/wiki/How-to-Flash-the-Firmware-Samples#soldering-vs-using-pogo-pins there is a link to X for the pogo pins. But the X Post https://x.com/rbaron_/status/1382226349088194560 is not available publicly...

**Comment by rbaron** [comment]
Nice catch, thanks @eiten. I updated the wiki with the direct embedded video. Let me know if that works.

**Comment by eiten** [comment]
Well, no... in Firefox (windows 10, ubuntu 22.04) it shows that it did not find a suitable video with supported format and MIME type 
![image](https://github.com/user-attachments/assets/762bd79c-aab0-46bb-9f33-59d787abdb42)
Edge (windows 11) and chrome (ubuntu 22.04) show the video window, but playing does not work (grayed out controls)
![image](https://github.com/user-attachments/assets/adc4d1b3-9dc3-4c4e-8a39-a1bfb45dea9c)

I think the problem is the QuickTime format of the video, I suppose only supported by Apple devices. I converted the video to webm and mp4 with settings for web, they should work:

https://github.com/user-attachments/assets/24300131-fa35-453f-aa76-d40abd2491b5

https://github.com/user-attachments/assets/9eb25976-7ec4-4ed1-84cf-cc9a35660156

And maybe you add a link to the ali article (maybe an affilate-Link ;)). I don't need it because i got Pogo-clamps in every count and pitch but others may be lucky if they don't have to search for them.

Regards, Edi

**Comment by eiten** [comment]
> I'm always frustrated when they eventually go stale.

Well, that's true...
