### ISSUE TITLE
R10 resistor partnumber in kicad file?

### ISSUE THREAD

**Issue by argupta23** [rbaron/b-parasite#23]
@rbaron,

Is the part number for the newly added R10 resistor in V1.2 of the PCB correct?

Can you please confirm or provide the updated info?

thanks

**Comment by rbaron** [comment]
Hi @argupta23, good catch, it's not correct. I will update it asap. It should refer to any 470 Ohm, 0402 resistor on LCSC.

**Comment by argupta23** [comment]
thanks
