### ISSUE TITLE
ble_monitor support in wiki/readme

### ISSUE THREAD

**Issue by jhbruhn** [rbaron/b-parasite#24]
I just added support for b-parasites to this handy Home Assistant Integration: https://github.com/custom-components/ble_monitor/pull/597
Allows slipping the ESPHome devices with manual configuration, although they can be used as "extension".
The integration discovers the parasites automatically and adds them as a HomeAssistant Device.

Maybe this integration can be mentioned in the wiki or readme as soon as a release with that PR was made.

**Comment by rbaron** [comment]
That looks fantastic @jhbruhn. Thanks for contributing again and happy new year!

I'll take the HA integration for a spin when I'm at my computer in a couple of days and I'll absolutely mention it in this repo.
