### ISSUE TITLE
Ordered 10 pcs from JLCPCB to Germany - do not need 10 - is there a platform for interested parties?

### ISSUE THREAD

**Issue by tispokes** [rbaron/b-parasite#41]
Hi,

the minimum quantity was 10 pcs because the SHTC3 was only available with a minimum of 10.
Is there some market place for this item?
Like to share the cost with no margin if someone need e.g. 5 pcs in Europe.

Don't know how it does behave with CC BY-SA 4.0 license and selling these PCBs (w/ or w/o software preinstalled)

**Comment by tpulatha** [comment]
Hi, I would be interested. Do you want to DM me on Twitter? Twitter.com/timurp

**Comment by tispokes** [comment]
@tpulatha sure, as soon as I got the ok from @rbaron

**Comment by rbaron** [comment]
Hey @tispokes, absolutely. Both the hardware and software licenses allow for this, as long as attribution is maintained. I'm happy to see people sharing their surplus units with others.

Happy hacking to both of you! And please consider sharing some pics with us in the "Community Gallery" issue when you get your boards up and running 👌

**Comment by crixionz** [comment]
Hi, I know it's been almost a year now, but is there still a chance you could sell me a unit you don't need?
I'm very new to all this, and I would like to get an idea whether I feel like this is something worth getting into (learning how to order PCBs, soldering the components, buying a j-link, learning to flash firmware, etc) before committing fully. 😅 

Also, what about the platform that was mentioned in this issue? Did anything like that pop up? I feel like a discord would be suitable, a place where everybody could offer their spare devices 😊

**Comment by tispokes** [comment]
@crixionz schreib mir auf Instagram, gleicher nick
