### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by schejbity** [rbaron/b-parasite#52]
When I turn on these variable, where or how can I these debug informations?

```
#define PRST_ADC_BATT_DEBUG 0
#define PRST_ADC_SOIL_DEBUG 0
#define PRST_BLE_DEBUG 0
#define PRST_SHT3C_DEBUG 0
#define PRST_ADC_PHOTO_DEBUG 0
```

**Comment by rbaron** [comment]
The firmware is [cconfigured](https://github.com/rbaron/b-parasite/blob/19f9a68b3b8ba1ed619a1f8829b4d243de257591/code/b-parasite/config/sdk_config.h#L7629) to output logs using [Segger's RTT protocol](https://www.segger.com/products/debug-probes/j-link/technology/about-real-time-transfer/).

I use the `JLinkRTTLogger` command line utility to read it on macOS.
