### ISSUE TITLE
Questions: Can I use E73-2G4M08S1EX to replace out of stock E73-2G4M08S1C on JLCPCB website?

### ISSUE THREAD

**Issue by Metus88** [rbaron/b-parasite#60]
I read [here](https://github.com/rbaron/b-parasite/issues/54#issuecomment-1238216780) , [issue54](https://github.com/rbaron/b-parasite/issues/54) that maybe it is possible use variant with `E` (https://github.com/rbaron/b-parasite/pull/13#issue-986752540)

- Someone can confirm me that it is compatible also with **E73-2G4M08S1EX**  ?
- I have to buy also a external antenna or is it optional? (maybe I need only if I want use wifi 2.4GH?) If I turn on without antenna I destroy the chip?
- The firmware will be the same?

Thanks for answering this noob's questions

**Comment by rbaron** [comment]
> Someone can confirm me that it is compatible also with E73-2G4M08S1EX ?

I haven't tried it myself, but @SystemFuchs [used the CX version](https://github.com/rbaron/b-parasite/issues/46#issuecomment-1222431433) successfully.

I took a quick look the datasheet of the EX and comparing it with the E, it seems like it should work, except the pin assignment looks equal to the C version. The only practical difference is pin 2, which the E version connects to the P0.25 and the C and EX versions connect to P1.10. Please double check the other pins.

> I have to buy also a external antenna or is it optional?

I believe the antenna is mandatory. Andreas Spiess [says](https://youtu.be/J3PBL9oLPX8?t=1045) it's better to always have an antenna connected. I trust him.

> The firmware will be the same?

I haven't tried to be 100% sure, but I would think so.
