### ISSUE TITLE
Open source the rotisserie / drying jig

### ISSUE THREAD

**Issue by rbaron** [rbaron/b-parasite#63]
A while ago I built this extremely questionable spinning jig to try and get the coating layer to dry more uniformly:

![rotisserie](https://user-images.githubusercontent.com/1573409/193142550-da63a2c3-0d00-4ff0-b116-d701a494ab44.jpg)

I wrote about it in [a twitter thread](https://twitter.com/rbaron_/status/1491467468996431873) and to my surprise more people wanted to join in on the fun. Fair warning: don't take it too seriously.

**Comment by jhbruhn** [comment]
How in-sync are the stl-files with the device on the picture you posted? I am trying to build a rotissierie but my moter seems to have a smaller radius than the one you used, could be AliExpress randomness-factor though. But it seems that in the picture, the case has an additional box between the cases body and the gears which could lead to a better fitting motor. Or is the motor held in place by more than just a friction fit?

Also, it seems that the .step file only contains the lid.

**Comment by rbaron** [comment]
I think they are pretty much in sync. Did you check the [gear_motor.stl](https://github.com/rbaron/b-parasite/blob/main/experimental/rotisserie/gear_motor.stl) (which is different from [gear.stl](https://github.com/rbaron/b-parasite/blob/main/experimental/rotisserie/gear.stl))? The `gear_motor.stl` has a notch and is a tight fit with the motor axis.

I just measured my motor and the axis is 4mm, the same as [this on Aliexpress](https://www.aliexpress.com/item/32987942205.html).

**Comment by jhbruhn** [comment]
Yes, I meant the body of the motor itself, not the motors axis.

**Comment by rbaron** [comment]
![rot1](https://user-images.githubusercontent.com/1573409/200638722-c56e5d40-10c2-4e74-847c-da5bf8828abc.jpg)
![rot2](https://user-images.githubusercontent.com/1573409/200638762-d5b6cfd2-56be-4e54-a347-ea900ea2cc97.jpg)

Do these help?

**Comment by jhbruhn** [comment]
Yes, thanks. Perhaps I am missing something, but is that connector between the motor and the other axes missing from the repo?

**Comment by rbaron** [comment]
You're right! I just added it to the repo as `base.stl`.

**Comment by jhbruhn** [comment]
Thanks!

**Comment by gniezen** [comment]
I finally have all the parts and I'm in the process of building it, but have some questions:

- All the holes on `base.stl` are the same size. Should I drill out the two holes for the motor and its screw myself?
- There's no hole in the lid for the power supply jack. Should I drill this myself?
- There's no hole for the speed controller knob in the case. Should I drill this myself?

**Comment by rbaron** [comment]
@gniezen As far as I can remember I think I drilled these holes myself. It's been a while 😰

**Comment by gniezen** [comment]
It's working! :tada: 

![IMG_20230317_125916](https://user-images.githubusercontent.com/418233/225919474-e3b8464b-90fa-40d1-8a58-4d80f510f3cb.jpg)
