### ISSUE TITLE
Missing Components in Current BOM

### ISSUE THREAD

**Issue by dannyjim-ml** [rbaron/b-parasite#72]
The current BOM is missing entries for U2, U3, R3, R5, and C6 which means they do not get populated when ordering from a fab, is this intentional? Still wrapping my head around the sensor design and was looking to order some when I caught this, thanks for your work!
![image](https://user-images.githubusercontent.com/57722475/201567215-810230a3-fc37-4232-baa6-ebe5953707af.png)

![image](https://user-images.githubusercontent.com/57722475/201567328-08a020e4-e146-4af0-8b92-43e40cdc3504.png)

![image](https://user-images.githubusercontent.com/57722475/201567470-6305e982-0660-4d15-8899-d10eef30452d.png)

**Comment by rbaron** [comment]
That was a mistake from my side. It should be fixed now.
