### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by BeckmaR** [rbaron/b-parasite#77]
Hi,
let me start by thanking you for developing this sensor. Building it wasn't easy, but a fun experience overall.

I have a question about the measured soil moisture. My sensors has reported values in the 20% area in the past, so I can confirm it's working in general. Since watering the plant, the value has gone up to 100%, and not gone down since (sensor is still working of course). The soil feels quite dry to me, so I would assume a value of 50% or something would be more adequate.

Is there anything I can do to influence the calibration, or verify my sensor is working correctly? Is there a bring-up routine somewhere?

**Comment by rbaron** [comment]
Have you coated your boards? We've seem some strange stuff happen (#50, #2) to uncoated boards, likely doing to water creeping in between the layers/under the solder mask.
