### ISSUE TITLE
Zigbee sample fails to build

### ISSUE THREAD

**Issue by andresp** [rbaron/b-parasite#94]
While trying to build for an nrf 52840-1.2 with nrf connect sdk 2.2.0, I'm getting the following error from CMake:

```
warning: IEEE802154_NRF5_FCS_IN_LENGTH (defined at drivers/ieee802154/Kconfig.nrf5:65) has direct dependencies IEEE802154_NRF5 && IEEE802154 with value n, but is currently being y-selected by the following symbols:
 - NET_L2_ZIGBEE (defined at C:/ncs/v2.2.0/nrf\subsys\zigbee/Kconfig:29), with value y, direct dependencies NETWORKING && ZIGBEE (value: y), and select condition NETWORKING && ZIGBEE (value: y)

error: Aborting due to Kconfig warnings

CMake Error at C:/ncs/v2.2.0/zephyr/cmake/modules/kconfig.cmake:328 (message):
```

Unfortunately, I'm unfamiliar with CMake and Kconfig. Any help would be appreciated.

**Comment by kenny00111** [comment]
I had the same issue with the 2.2.0 SDK, it works with the 2.1.2

**Comment by andresp** [comment]
Can confirm, worked with 2.1.2.

**Comment by RobertLukan** [comment]
Same for me.

**Comment by MJDSys** [comment]
It appears SDK 2.2.0 changed such that the device tree needs to enable 802.15.4 support.  I have a patch locally, but I'm waiting for hardware to arrive to try flashing and confirm it's working.  I can try submitting a PR once I know my changes are good.
