### ISSUE TITLE
Zigbee fails to join the network

### ISSUE THREAD

**Issue by RobertLukan** [rbaron/b-parasite#96]
This issue I guess is really not an issue, but maybe somebody will find this information helpful. I just could not get Zigbee software working for a while. Everything looked OK, but probe would not join the network, speaking more precisely, it would try to join but leave very quickly. 

After a bit of googling, I notice that someone else has a similar problem, [https://devzone.nordicsemi.com/f/nordic-q-a/83640/zigbee-router-leaves-network-autonomously-after-few-seconds](url).

I am using Sonoff USB Dongle Plus with Zigbee2Mqtt. I noticed that software is still not fully supported, so maybe that is the problem. Nevertheless, by adding option shown below in main.c, probe joined the network without a problem and it is working OK so far.
 
zb_bdb_set_legacy_device_support(1);

**Comment by rbaron** [comment]
Thanks for the tip @RobertLukan.
