### ISSUE TITLE
Building with Docker gives `cmake` error

### ISSUE THREAD

**Issue by ryall** [rbaron/b-parasite#97]
Running this as per the Wiki:

`docker run --rm -v ${PWD}:/code -w /code/samples/ble nordicplayground/nrfconnect-sdk:v2.1-branch west build --build-dir ./build --pristine --board bparasite_nrf52840@1.2.0`

Getting the following error:

```
-- west build: generating a build system
FATAL ERROR: cannot get cmake version: Command '['/usr/local/bin/cmake', '--version']' returned non-zero exit status 1.
```

**Comment by rbaron** [comment]
@ryall we updated instructions for the 2.2 SDK. Let us know if it works for you.
